package com.example.gateway.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MunicipalityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMunicipalityAllPropertiesEquals(Municipality expected, Municipality actual) {
        assertMunicipalityAutoGeneratedPropertiesEquals(expected, actual);
        assertMunicipalityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMunicipalityAllUpdatablePropertiesEquals(Municipality expected, Municipality actual) {
        assertMunicipalityUpdatableFieldsEquals(expected, actual);
        assertMunicipalityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMunicipalityAutoGeneratedPropertiesEquals(Municipality expected, Municipality actual) {
        assertThat(actual)
            .as("Verify Municipality auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMunicipalityUpdatableFieldsEquals(Municipality expected, Municipality actual) {
        assertThat(actual)
            .as("Verify Municipality relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getRegion()).as("check region").isEqualTo(expected.getRegion()))
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMunicipalityUpdatableRelationshipsEquals(Municipality expected, Municipality actual) {
        // empty method
    }
}
